### PR TITLE
Updated homepage animation

### PR DESCRIPTION
**Pull request by TishShaw**
This pull request  focuses on the animation of ghost characters and the styling of control buttons on the homepage. Key changes include:

1. **Ghost Animation Adjustments**:
    - Modified the `.ghost` class to implement a new 'floating' animation effect (`bouncing` keyframe).
    - Adjusted the `moveGhost` animation for a smoother movement across the screen.
    - Added a 'pause on hover' functionality to the ghosts (`animation-play-state: paused`), enhancing interactivity.

2. **Button Styling Enhancements**:
    - Improved the visual appeal of `.home-start-button` and `.home-howTo-button` with padding and font size adjustments for better user experience.
    - Added hover effects to these buttons for better interactivity (background color changes to dark red).

3. **Pac-Man Animation Tweaks**:
    - Updated the `moveForward` keyframes to include a rotation effect, making Pac-Man turn around once at the midpoint of its path and then continue in the new direction.

### CODE REVIEW

**Comment by AdventureBear** [comment]
Great job with the reversal!!    and it's before 5pm!   :)

**Comment by AdventureBear** [comment]
for further polishing, is it possible to have them come into the frame a little sooner? Seems  like there is a slight delay, and I know you mentioned this so its probably a challenge, but i think the dots really help it be identified as pac man, even without the animations.   I feel like if they were there even as he moved across them i twould be more iconic.   Curiosu what other people think

**Comment by TishShaw** [comment]
@AdventureBear Absolutely. I have the dots commented out in the css so i'll just uncomment that and work on the eating animation as a stretch goal.

**Review by KatrinaWright — APPROVED** [review]
I'm curious about your end goal with the two bouncing ghosts are - is that for choosing single and multiplayer modes? It distracts me somewhat that the black field is a different size when the initial chasing animation happens versus the floating ghosts - which element would need to be tweaked to have the animation zone be the same size as the eventual board, so that the jarring resizing doesn't happen? 

Super cool though! Like, these are not criticisms - these are just curious thoughts inspired by the change ^_^ Well done!! I love your work <3

**Pull request merged**
