### PR TITLE
Refactored GameArea and PlayerMovement components, updated ghost starting positions

### PR DESCRIPTION
**Pull request by TishShaw**
## Summary
This pull request introduces a series of refactorings and optimizations to the `GameArea` and `PlayerMovement` components of the `reverse-pacman` project. The goal is to enhance code readability, maintainability, and performance.

### GameArea.css
- **Addition**: Added `position: relative` to the `.board` class for better positioning control.

### GameArea.jsx
- **Refactoring**: Reduced the size of the `GameArea` component by removing redundant code and comments. 
- **Enhancement**: Integrated `maze` data directly from the `../utils/data.js` file to streamline the component's structure.
- **Optimization**: Simplified the rendering logic of the maze, improving both readability and performance.

### PlayerMovement.jsx
- **Major Refactoring**: Overhauled the player movement logic to be more efficient and less error-prone.
- **New Feature**: Implemented a dynamic calculation of the grid cell size based on the board dimensions, ensuring a more responsive and adaptable game interface.
- **Improvement**: Enhanced player movement handling by incorporating a more robust grid-based movement system, replacing the previous pixel-based approach.

### data.js
- **Addition**: Introduced a new file `data.js` under `src/utils`, containing the static maze data for ease of management and modification.

### CODE REVIEW

**Comment by AdventureBear** [comment]
I am mobile, so I can’t review it right now. But based on your excellent
documentation, I’m ready to merge it right now, without testing, lol. I
will be home in a couple of hours and can review it if no one else is able
to do it in that time frame.

 in the meantime, what I like to do is create a new branch off this one
you’ve just done so you have your current code, and continue working on
whatever you like next!


Suzanne Atkinson, MD
Clinical Instructor of Emergency Medicine
University of Pittsburgh School of Medicine

*Head Coach & Founder*
Steel City Endurance Coaching
Tri Coach Academy
USA Triathlon Level 3 Coach

*Assistant Coach*
Duquesne University Women's Triathlon Team
NCAA Division 1, Atlantic 10 Conference

**Comment by kbrenn02** [comment]
Screen Shot 2024-01-03 at 3 40 47 PM
This is really amazing! Great job! 

I was testing the player movements, trying to stay on the path, and I noticed that at some parts, the path that was shown was off from the path that the players could travel. What I mean by this is, players were still limited to the confines of the maze, but the maze that was shown and the maze they could travel did not line up

**Comment by TishShaw** [comment]
@kbrenn02 Thank you so much for your feedback! My main focus for this ticket was to create the starting position for the ghost and confine them in the middle of the game. I recently made another pull request for ticket #15 that actually fixes this bug.

**Review by AdventureBear — APPROVED** [review]
This is frickin' amazing.  GOOD WORK!   There is a little bug with the blue player's collisin detection being off by 1 tile/column, but I am going to recommend merging this still, as it's a quick (hopefully) bug fix.

**Pull request merged**
